# Generated by Django 5.1.1 on 2024-09-27 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detect", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="image_for_pred",
            new_name="image",
        ),
    ]
